ExamPrepST2/csharp/CatShop/Models/Cat.cs
namespace CatShop.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Cat
    {
        // TODO

        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Nickname { get; set; }

        [Required]
        public double Price { get; set; }

    }
}

ExamPrepST2/csharp/CatShop/Models/CatDbContext.cs
namespace CatShop.Models
{
    using Microsoft.EntityFrameworkCore;

    public class CatDbContext : DbContext
    {
        public DbSet<Cat> Cats { get; set; }

        public CatDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySQL("server=localhost;database=catshop_csharp;user=root;");
        }
    }
}

ExamPrepST2/csharp/CatShop/Controllers/CatController.cs
namespace CatShop.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using CatShop.Models;
    using System.Linq;

    public class CatController : Controller
    {
        private readonly CatDbContext context;

        public CatController(CatDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            // TODO
            var cats = context.Cats.ToList();
            return View(cats);
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            // TODO
            return View();
        }

        [HttpPost]
        [Route("create")]
        public ActionResult Create(Cat cat)
        {
            this.context.Update(cat);
            this.context.SaveChanges();
            return Redirect("/");
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int id)
        {
            // TODO
            var cat = this.context.Cats.Find(id);
            return View(cat);
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm(int id, Cat catModel)
        {
            // TODO
            this.context.Update(catModel);
            this.context.SaveChanges();
            return Redirect("/");
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int id)
        {
            // TODO
            var cat = this.context.Cats.Find(id);
            return View(cat);
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id, Cat catModel)
        {
            // TODO
            this.context.Cats.Remove(catModel);
            this.context.SaveChanges();
            return Redirect("/");
        }
    }
}

ExamPrepST2/csharp/CatShop/Views/Cat/Create.cshtml
@model CatShop.Models.Cat

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Cat", FormMethod.Post, new { @class = "cat-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Add Cat
        </div>
        <div class="create-name">
            <div class="create-name-label">Name</div>
            <input class="create-name-content" name="name" />
        </div>
        <div class="create-nickname">
            <div class="create-nickname-label">Nickname</div>
            <input class="create-nickname-content" name="nickname" />
        </div>
        <div class="create-price">
            <div class="create-price-label">Price</div>
            <input type="number" min="0" step="0.00001" class="create-price-content" name="price" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Add Cat</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

ExamPrepST2/csharp/CatShop/Views/Cat/Delete.cshtml
@model CatShop.Models.Cat

@{
    ViewBag.Title = "Delete";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Cat", FormMethod.Post, new { @class = "cat-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Delete Cat
        </div>
        <div class="create-name">
            <div class="create-name-label">Name</div>
            <input class="create-name-content" name="name" value="@Model.Name" disabled="disabled" />
        </div>
        <div class="create-nickname">
            <div class="create-nickname-label">Nickname</div>
            <input class="create-nickname-content" name="nickname" disabled="disabled" value="@Model.Nickname"/>
        </div>
        <div class="create-price">
            <div class="create-price-label">Price</div>
            <input type="number" min="0" class="create-price-content" name="price" value="@Model.Price" disabled="disabled" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Delete Cat</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

ExamPrepST2/csharp/CatShop/Views/Cat/Edit.cshtml
@model CatShop.Models.Cat

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Cat", FormMethod.Post, new { @class = "cat-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Cat
        </div>
        <div class="create-name">
            <div class="create-name-label">Name</div>
            <input class="create-name-content" name="name" value="@Model.Name" />
        </div>
        <div class="create-nickname">
            <div class="create-nickname-label">Nickname</div>
            <input class="create-nickname-content" name="nickname" value="@Model.Nickname"/>
        </div>
        <div class="create-price">
            <div class="create-price-label">Price</div>
            <input type="number" min="0" step="0.00001" class="create-price-content" name="price" value="@Model.Price" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Edit Cat</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

ExamPrepST2/csharp/CatShop/Views/Cat/Index.cshtml
@model List<CatShop.Models.Cat>
@{
    ViewBag.Title = "Index";
}
<div class="wrapper">
    <div class="cat-create">
        <div class="create-header">
            Cat Shop
        </div>
    </div>
    <br />
    <div class="button-holder">
        <a type="button" href="/create" class="log-button">Add Cat</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="cat-label">Cat</div>
            <div class="nickname-label">Nickname</div>
            <div class="price-label">Price</div>
            <div class="actions-label">Actions</div>
        </div>
        <div class="main">
            @foreach (var cat in Model.ToList())
            {
                <div class="cat">
                    <div class="cat-name">
                        @(cat.Name)
                    </div>
                    <div class="cat-nickname">
                        @(cat.Nickname)
                    </div>
                    <div class="cat-price">
                        @(cat.Price)
                    </div>
                    <div class="cat-actions">
                        @Html.ActionLink("Edit", "Edit", "Cat", new { id = cat.Id }, new { @class = "edit-button" })
                        @Html.ActionLink("Delete", "Delete", "Cat", new { id = cat.Id }, new { @class = "delete-button" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ExamPrepST2/csharp/CatShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Cat Shop</title>
    <link rel="stylesheet" href="~/css/reset.css" type="text/css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/cat-style.css" type="text/css" />
</head>
<body>
    @RenderBody()
</body>
</html>